// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMXqr-AVwm2K5jWWIssOcccymnu3odhpE',
    appId: '1:1054774797672:web:c2b6a3aff87f46474c22dd',
    messagingSenderId: '1054774797672',
    projectId: 'instagramclone-b74df',
    authDomain: 'instagramclone-b74df.firebaseapp.com',
    storageBucket: 'instagramclone-b74df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBem7DFaYSQm-NB9dwXXKYTZ4zz1zTRkPw',
    appId: '1:1054774797672:android:a15c6dd34aa5f4194c22dd',
    messagingSenderId: '1054774797672',
    projectId: 'instagramclone-b74df',
    storageBucket: 'instagramclone-b74df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXqAJTUEdUZfLP-PupiEZ_6GvIr7P1wUk',
    appId: '1:1054774797672:ios:d066dcd937e686064c22dd',
    messagingSenderId: '1054774797672',
    projectId: 'instagramclone-b74df',
    storageBucket: 'instagramclone-b74df.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXqAJTUEdUZfLP-PupiEZ_6GvIr7P1wUk',
    appId: '1:1054774797672:ios:234579ba15ff72aa4c22dd',
    messagingSenderId: '1054774797672',
    projectId: 'instagramclone-b74df',
    storageBucket: 'instagramclone-b74df.appspot.com',
    iosBundleId: 'com.example.instagramApp.RunnerTests',
  );
}
